import { PipelineState } from './types';

const now = new Date();
const fmt = (offset: number) => new Date(now.getTime() - offset * 1000).toISOString();

export const mockData: PipelineState = {
  progress: {
    current_phase: 3,
    current_step: 'Conditioning agent 7/12',
    phase_name: 'Conditioning & Validation',
    steps_completed: 18,
    total_steps: 28,
    progress_percent: 64.3,
    estimated_remaining_seconds: 2340,
    last_action: 'Completed conditioning round 3 for Agent Marcus',
    last_action_timestamp: fmt(12),
  },
  costs: {
    total_cost: 18.42,
    opus_cost: 14.2,
    sonnet_cost: 3.72,
    embedding_cost: 0.5,
    cost_by_phase: {
      'Phase 1': 2.15,
      'Phase 2': 5.87,
      'Phase 3': 10.4,
      'Phase 4': 0,
    },
    cost_by_agent: {
      'agent-01': 2.1,
      'agent-02': 1.85,
      'agent-03': 1.92,
      'agent-04': 2.34,
      'agent-05': 1.67,
      'agent-06': 2.08,
      'agent-07': 1.59,
      'agent-08': 0,
      'agent-09': 0,
      'agent-10': 0,
      'agent-11': 0,
      'agent-12': 0,
    },
    total_input_tokens: 1247830,
    total_output_tokens: 389210,
    total_api_calls: 342,
    opus_calls: 128,
    sonnet_calls: 214,
    avg_cost_per_opus_call: 0.111,
    avg_cost_per_sonnet_call: 0.0174,
    estimated_total_cost: 28.75,
    budget_remaining: 56.58,
    cost_over_time: Array.from({ length: 20 }, (_, i) => ({
      timestamp: fmt((20 - i) * 300),
      cumulative_cost: +(i < 10
        ? (i * 0.8 + Math.random() * 0.3)
        : (8 + (i - 10) * 1.05 + Math.random() * 0.3)).toFixed(2),
      model: i % 3 === 0 ? 'opus' : 'sonnet',
    })),
  },
  agents: [
    {
      id: 'agent-01',
      tier1: {
        name: 'Marcus Thompson',
        age: 34,
        hometown: 'Atlanta, GA',
        occupation: 'Personal Trainer',
        archetype: 'Alpha Competitor',
        secondary_archetype: 'Reluctant Leader',
        conflict_style: 'Confrontational',
        core_values: ['Loyalty', 'Strength', 'Honesty'],
        deepest_fears: ['Being seen as weak', 'Abandonment'],
        speech_pattern: { catchphrases: ['At the end of the day', 'Real talk'], vocabulary_level: 'casual' },
        big_five: { openness: 0.45, conscientiousness: 0.72, extraversion: 0.88, agreeableness: 0.35, neuroticism: 0.41 },
      },
      conditioning_status: 'passed',
      validation_scores: { persona_consistency: 87, behavioral_distinctiveness: 22, strategic_depth: 74, emotional_authenticity: 81, anti_drift: 89 },
      interactions_completed: 24,
      token_count: 48200,
    },
    {
      id: 'agent-02',
      tier1: {
        name: 'Sofia Reyes',
        age: 27,
        hometown: 'Miami, FL',
        occupation: 'Social Media Influencer',
        archetype: 'Social Butterfly',
        secondary_archetype: 'Hidden Strategist',
        conflict_style: 'Avoidant-Passive',
        core_values: ['Authenticity', 'Connection', 'Beauty'],
        deepest_fears: ['Irrelevance', 'Being alone'],
        speech_pattern: { catchphrases: ['Literally dying', 'Not gonna lie'], vocabulary_level: 'millennial' },
        big_five: { openness: 0.82, conscientiousness: 0.38, extraversion: 0.95, agreeableness: 0.71, neuroticism: 0.62 },
      },
      conditioning_status: 'passed',
      validation_scores: { persona_consistency: 92, behavioral_distinctiveness: 18, strategic_depth: 68, emotional_authenticity: 85, anti_drift: 91 },
      interactions_completed: 22,
      token_count: 45100,
    },
    {
      id: 'agent-03',
      tier1: {
        name: 'David Chen',
        age: 41,
        hometown: 'San Francisco, CA',
        occupation: 'Software Engineer',
        archetype: 'Quiet Observer',
        secondary_archetype: 'Intellectual Strategist',
        conflict_style: 'Analytical-Detached',
        core_values: ['Logic', 'Privacy', 'Fairness'],
        deepest_fears: ['Chaos', 'Emotional vulnerability'],
        speech_pattern: { catchphrases: ['Statistically speaking', 'Let me think about that'], vocabulary_level: 'technical' },
        big_five: { openness: 0.78, conscientiousness: 0.89, extraversion: 0.22, agreeableness: 0.55, neuroticism: 0.31 },
      },
      conditioning_status: 'passed',
      validation_scores: { persona_consistency: 94, behavioral_distinctiveness: 15, strategic_depth: 88, emotional_authenticity: 63, anti_drift: 86 },
      interactions_completed: 20,
      token_count: 42300,
    },
    {
      id: 'agent-04',
      tier1: {
        name: 'Jasmine Williams',
        age: 23,
        hometown: 'Houston, TX',
        occupation: 'Nursing Student',
        archetype: 'Empathic Caretaker',
        secondary_archetype: 'Underestimated Player',
        conflict_style: 'Mediator',
        core_values: ['Compassion', 'Family', 'Faith'],
        deepest_fears: ['Failure', 'Letting others down'],
        speech_pattern: { catchphrases: ['Bless your heart', 'I just feel like'], vocabulary_level: 'warm-colloquial' },
        big_five: { openness: 0.61, conscientiousness: 0.75, extraversion: 0.67, agreeableness: 0.92, neuroticism: 0.58 },
      },
      conditioning_status: 'passed',
      validation_scores: { persona_consistency: 89, behavioral_distinctiveness: 24, strategic_depth: 62, emotional_authenticity: 91, anti_drift: 82 },
      interactions_completed: 21,
      token_count: 44800,
    },
    {
      id: 'agent-05',
      tier1: {
        name: 'Brett Kowalski',
        age: 29,
        hometown: 'Chicago, IL',
        occupation: 'Bartender / Aspiring Comedian',
        archetype: 'Class Clown',
        secondary_archetype: 'Emotional Deflector',
        conflict_style: 'Humor-Deflection',
        core_values: ['Fun', 'Freedom', 'Acceptance'],
        deepest_fears: ['Being taken seriously', 'Rejection'],
        speech_pattern: { catchphrases: ['Bro literally', 'That is hilarious'], vocabulary_level: 'bro-casual' },
        big_five: { openness: 0.73, conscientiousness: 0.28, extraversion: 0.91, agreeableness: 0.68, neuroticism: 0.52 },
      },
      conditioning_status: 'passed',
      validation_scores: { persona_consistency: 83, behavioral_distinctiveness: 19, strategic_depth: 55, emotional_authenticity: 72, anti_drift: 78 },
      interactions_completed: 23,
      token_count: 46700,
    },
    {
      id: 'agent-06',
      tier1: {
        name: 'Victoria Ashford',
        age: 38,
        hometown: 'Greenwich, CT',
        occupation: 'Corporate Attorney',
        archetype: 'Ice Queen Strategist',
        secondary_archetype: 'Vulnerable Perfectionist',
        conflict_style: 'Calculated-Assertive',
        core_values: ['Excellence', 'Control', 'Respect'],
        deepest_fears: ['Imperfection', 'Loss of control'],
        speech_pattern: { catchphrases: ['With all due respect', 'The facts speak for themselves'], vocabulary_level: 'formal-precise' },
        big_five: { openness: 0.42, conscientiousness: 0.95, extraversion: 0.55, agreeableness: 0.18, neuroticism: 0.47 },
      },
      conditioning_status: 'passed',
      validation_scores: { persona_consistency: 96, behavioral_distinctiveness: 12, strategic_depth: 92, emotional_authenticity: 67, anti_drift: 94 },
      interactions_completed: 25,
      token_count: 51200,
    },
    {
      id: 'agent-07',
      tier1: {
        name: 'Terrence "TJ" Jackson',
        age: 26,
        hometown: 'Detroit, MI',
        occupation: 'Youth Basketball Coach',
        archetype: 'Loyal Soldier',
        secondary_archetype: 'Moral Compass',
        conflict_style: 'Protective-Reactive',
        core_values: ['Community', 'Respect', 'Growth'],
        deepest_fears: ['Betrayal', 'Becoming like his father'],
        speech_pattern: { catchphrases: ['On everything I love', 'Facts though'], vocabulary_level: 'urban-authentic' },
        big_five: { openness: 0.51, conscientiousness: 0.67, extraversion: 0.74, agreeableness: 0.63, neuroticism: 0.44 },
      },
      conditioning_status: 'in_progress',
      validation_scores: { persona_consistency: 78, behavioral_distinctiveness: 28, strategic_depth: 58, emotional_authenticity: 70, anti_drift: 72 },
      interactions_completed: 14,
      token_count: 31500,
    },
    {
      id: 'agent-08',
      tier1: {
        name: 'Heather Dawson',
        age: 45,
        hometown: 'Nashville, TN',
        occupation: 'Real Estate Agent',
        archetype: 'Southern Manipulator',
        secondary_archetype: 'Wounded Survivor',
        conflict_style: 'Passive-Aggressive',
        core_values: ['Security', 'Appearances', 'Family legacy'],
        deepest_fears: ['Poverty', 'Being exposed as fraud'],
        speech_pattern: { catchphrases: ['Well I never', 'Sugar, let me tell you'], vocabulary_level: 'southern-polished' },
        big_five: { openness: 0.34, conscientiousness: 0.71, extraversion: 0.78, agreeableness: 0.45, neuroticism: 0.66 },
      },
      conditioning_status: 'failed',
      validation_scores: { persona_consistency: 72, behavioral_distinctiveness: 35, strategic_depth: 48, emotional_authenticity: 54, anti_drift: 68 },
      interactions_completed: 18,
      token_count: 38900,
    },
    {
      id: 'agent-09',
      tier1: {
        name: 'Kai Nakamura',
        age: 31,
        hometown: 'Portland, OR',
        occupation: 'Environmental Scientist',
        archetype: 'Idealistic Outsider',
        secondary_archetype: 'Reluctant Competitor',
        conflict_style: 'Principled-Stubborn',
        core_values: ['Sustainability', 'Truth', 'Justice'],
        deepest_fears: ['Hypocrisy', 'Selling out'],
        speech_pattern: { catchphrases: ['That is problematic', 'We need to talk about'], vocabulary_level: 'academic-casual' },
        big_five: { openness: 0.94, conscientiousness: 0.62, extraversion: 0.41, agreeableness: 0.57, neuroticism: 0.53 },
      },
      conditioning_status: 'not_started',
      validation_scores: {},
      interactions_completed: 0,
      token_count: 0,
    },
    {
      id: 'agent-10',
      tier1: {
        name: 'Daniella Cruz',
        age: 33,
        hometown: 'Phoenix, AZ',
        occupation: 'ER Nurse',
        archetype: 'Tough Cookie',
        secondary_archetype: 'Secret Softie',
        conflict_style: 'Direct-Explosive',
        core_values: ['Toughness', 'Honesty', 'Survival'],
        deepest_fears: ['Vulnerability', 'Losing independence'],
        speech_pattern: { catchphrases: ['I am not here to make friends', 'Let me be real'], vocabulary_level: 'blunt-direct' },
        big_five: { openness: 0.38, conscientiousness: 0.81, extraversion: 0.62, agreeableness: 0.25, neuroticism: 0.71 },
      },
      conditioning_status: 'not_started',
      validation_scores: {},
      interactions_completed: 0,
      token_count: 0,
    },
    {
      id: 'agent-11',
      tier1: {
        name: 'Reverend James "Jimmy" Whitmore',
        age: 52,
        hometown: 'Savannah, GA',
        occupation: 'Retired Pastor',
        archetype: 'Wise Elder',
        secondary_archetype: 'Fallen Authority',
        conflict_style: 'Sermonic-Guilt',
        core_values: ['Faith', 'Redemption', 'Guidance'],
        deepest_fears: ['Irrelevance', 'Past sins being revealed'],
        speech_pattern: { catchphrases: ['The Lord works in mysterious ways', 'Now let me tell you something'], vocabulary_level: 'pastoral-folksy' },
        big_five: { openness: 0.55, conscientiousness: 0.78, extraversion: 0.69, agreeableness: 0.72, neuroticism: 0.39 },
      },
      conditioning_status: 'not_started',
      validation_scores: {},
      interactions_completed: 0,
      token_count: 0,
    },
    {
      id: 'agent-12',
      tier1: {
        name: 'Zara Okafor',
        age: 24,
        hometown: 'Brooklyn, NY',
        occupation: 'Fashion Design Student',
        archetype: 'Fiery Provocateur',
        secondary_archetype: 'Artistic Visionary',
        conflict_style: 'Confrontational-Expressive',
        core_values: ['Self-expression', 'Boldness', 'Originality'],
        deepest_fears: ['Mediocrity', 'Being silenced'],
        speech_pattern: { catchphrases: ['Period', 'Say less'], vocabulary_level: 'gen-z-creative' },
        big_five: { openness: 0.97, conscientiousness: 0.33, extraversion: 0.86, agreeableness: 0.29, neuroticism: 0.74 },
      },
      conditioning_status: 'not_started',
      validation_scores: {},
      interactions_completed: 0,
      token_count: 0,
    },
  ],
  health: {
    api_status: 'healthy',
    api_latency_ms: 245,
    rate_limit_remaining: 847,
    rate_limit_total: 1000,
    last_health_check: fmt(3),
    last_api_call: fmt(8),
    seconds_since_last_call: 8,
    error_log: [
      { timestamp: fmt(1800), error: 'Rate limit warning: 90% capacity reached' },
      { timestamp: fmt(3600), error: 'Temporary 503 from API, retried successfully' },
    ],
    is_stuck: false,
  },
  validation_results: [
    { agent_id: 'agent-01', benchmark: 'persona_consistency', score: 87, passed: true, details: 'Strong adherence to persona across all test scenarios' },
    { agent_id: 'agent-01', benchmark: 'behavioral_distinctiveness', score: 22, passed: true, details: 'Low overlap with other agent responses' },
    { agent_id: 'agent-01', benchmark: 'strategic_depth', score: 74, passed: true, details: 'Demonstrates multi-step strategic thinking' },
    { agent_id: 'agent-01', benchmark: 'emotional_authenticity', score: 81, passed: true, details: 'Emotional responses align with persona profile' },
    { agent_id: 'agent-01', benchmark: 'anti_drift', score: 89, passed: true, details: 'Maintains persona over extended conversations' },
    { agent_id: 'agent-02', benchmark: 'persona_consistency', score: 92, passed: true, details: 'Excellent persona adherence' },
    { agent_id: 'agent-02', benchmark: 'behavioral_distinctiveness', score: 18, passed: true, details: 'Highly distinct response patterns' },
    { agent_id: 'agent-02', benchmark: 'strategic_depth', score: 68, passed: true, details: 'Adequate strategic reasoning' },
    { agent_id: 'agent-02', benchmark: 'emotional_authenticity', score: 85, passed: true, details: 'Authentic emotional expression' },
    { agent_id: 'agent-02', benchmark: 'anti_drift', score: 91, passed: true, details: 'Very stable persona over time' },
    { agent_id: 'agent-03', benchmark: 'persona_consistency', score: 94, passed: true, details: 'Outstanding consistency' },
    { agent_id: 'agent-03', benchmark: 'behavioral_distinctiveness', score: 15, passed: true, details: 'Very distinct behavioral signature' },
    { agent_id: 'agent-03', benchmark: 'strategic_depth', score: 88, passed: true, details: 'Deep strategic analysis capability' },
    { agent_id: 'agent-03', benchmark: 'emotional_authenticity', score: 63, passed: true, details: 'Appropriately restrained emotional range' },
    { agent_id: 'agent-03', benchmark: 'anti_drift', score: 86, passed: true, details: 'Strong persona stability' },
    { agent_id: 'agent-04', benchmark: 'persona_consistency', score: 89, passed: true, details: 'Consistent caretaker persona' },
    { agent_id: 'agent-04', benchmark: 'behavioral_distinctiveness', score: 24, passed: true, details: 'Distinct from other agents' },
    { agent_id: 'agent-04', benchmark: 'strategic_depth', score: 62, passed: true, details: 'Meets minimum strategic threshold' },
    { agent_id: 'agent-04', benchmark: 'emotional_authenticity', score: 91, passed: true, details: 'Highly authentic emotional responses' },
    { agent_id: 'agent-04', benchmark: 'anti_drift', score: 82, passed: true, details: 'Good persona retention' },
    { agent_id: 'agent-05', benchmark: 'persona_consistency', score: 83, passed: true, details: 'Good consistency with humor persona' },
    { agent_id: 'agent-05', benchmark: 'behavioral_distinctiveness', score: 19, passed: true, details: 'Unique comedic behavioral patterns' },
    { agent_id: 'agent-05', benchmark: 'strategic_depth', score: 55, passed: false, details: 'Below threshold - humor overrides strategic thinking' },
    { agent_id: 'agent-05', benchmark: 'emotional_authenticity', score: 72, passed: true, details: 'Authentic but deflective emotional range' },
    { agent_id: 'agent-05', benchmark: 'anti_drift', score: 78, passed: true, details: 'Acceptable persona stability' },
    { agent_id: 'agent-06', benchmark: 'persona_consistency', score: 96, passed: true, details: 'Exceptional adherence to ice queen persona' },
    { agent_id: 'agent-06', benchmark: 'behavioral_distinctiveness', score: 12, passed: true, details: 'Extremely distinct response patterns' },
    { agent_id: 'agent-06', benchmark: 'strategic_depth', score: 92, passed: true, details: 'Superior strategic reasoning' },
    { agent_id: 'agent-06', benchmark: 'emotional_authenticity', score: 67, passed: true, details: 'Controlled emotional range consistent with persona' },
    { agent_id: 'agent-06', benchmark: 'anti_drift', score: 94, passed: true, details: 'Excellent long-term stability' },
    { agent_id: 'agent-07', benchmark: 'persona_consistency', score: 78, passed: false, details: 'Below threshold - needs more conditioning rounds' },
    { agent_id: 'agent-07', benchmark: 'behavioral_distinctiveness', score: 28, passed: true, details: 'Adequately distinct' },
    { agent_id: 'agent-07', benchmark: 'strategic_depth', score: 58, passed: false, details: 'Below threshold - too reactive, not strategic enough' },
    { agent_id: 'agent-07', benchmark: 'emotional_authenticity', score: 70, passed: true, details: 'Good emotional authenticity' },
    { agent_id: 'agent-07', benchmark: 'anti_drift', score: 72, passed: false, details: 'Below threshold - persona drifts in long exchanges' },
    { agent_id: 'agent-08', benchmark: 'persona_consistency', score: 72, passed: false, details: 'Inconsistent persona - breaks character under pressure' },
    { agent_id: 'agent-08', benchmark: 'behavioral_distinctiveness', score: 35, passed: false, details: 'Too similar to agent-06 response patterns' },
    { agent_id: 'agent-08', benchmark: 'strategic_depth', score: 48, passed: false, details: 'Lacks strategic reasoning depth' },
    { agent_id: 'agent-08', benchmark: 'emotional_authenticity', score: 54, passed: false, details: 'Emotional responses feel artificial' },
    { agent_id: 'agent-08', benchmark: 'anti_drift', score: 68, passed: false, details: 'Significant persona drift detected' },
  ],
  events: [
    { timestamp: fmt(5), phase: 'Phase 3', agent_id: 'agent-07', event_type: 'info', message: 'Starting conditioning round 4 for TJ Jackson' },
    { timestamp: fmt(12), phase: 'Phase 3', agent_id: 'agent-07', event_type: 'info', message: 'Completed conditioning round 3 - persona consistency improving' },
    { timestamp: fmt(25), phase: 'Phase 3', agent_id: 'agent-07', event_type: 'warning', message: 'Anti-drift score 72% below threshold, scheduling additional rounds' },
    { timestamp: fmt(40), phase: 'Phase 3', agent_id: 'agent-08', event_type: 'error', message: 'Agent Heather Dawson FAILED validation - 5/5 benchmarks below threshold' },
    { timestamp: fmt(55), phase: 'Phase 3', agent_id: 'agent-08', event_type: 'warning', message: 'Behavioral distinctiveness too high (35%) - overlaps with Victoria Ashford' },
    { timestamp: fmt(70), phase: 'Phase 3', agent_id: 'agent-08', event_type: 'info', message: 'Re-conditioning attempt 2 for Heather Dawson' },
    { timestamp: fmt(90), phase: 'Phase 3', agent_id: 'agent-06', event_type: 'success', message: 'Agent Victoria Ashford PASSED all 5 benchmarks' },
    { timestamp: fmt(120), phase: 'Phase 3', agent_id: 'agent-05', event_type: 'warning', message: 'Strategic depth 55% below 60% threshold - borderline' },
    { timestamp: fmt(140), phase: 'Phase 3', agent_id: 'agent-05', event_type: 'success', message: 'Agent Brett Kowalski passed 4/5 benchmarks (strategic depth waived)' },
    { timestamp: fmt(180), phase: 'Phase 3', agent_id: 'agent-04', event_type: 'success', message: 'Agent Jasmine Williams PASSED all 5 benchmarks' },
    { timestamp: fmt(210), phase: 'Phase 3', agent_id: 'agent-03', event_type: 'success', message: 'Agent David Chen PASSED all 5 benchmarks' },
    { timestamp: fmt(260), phase: 'Phase 3', agent_id: 'agent-02', event_type: 'success', message: 'Agent Sofia Reyes PASSED all 5 benchmarks' },
    { timestamp: fmt(310), phase: 'Phase 3', agent_id: 'agent-01', event_type: 'success', message: 'Agent Marcus Thompson PASSED all 5 benchmarks' },
    { timestamp: fmt(380), phase: 'Phase 3', agent_id: null, event_type: 'info', message: 'Beginning Phase 3: Conditioning & Validation' },
    { timestamp: fmt(420), phase: 'Phase 2', agent_id: null, event_type: 'success', message: 'Phase 2 complete: 12 agent personas generated' },
    { timestamp: fmt(480), phase: 'Phase 2', agent_id: 'agent-12', event_type: 'info', message: 'Generated persona: Zara Okafor (Fiery Provocateur)' },
    { timestamp: fmt(510), phase: 'Phase 2', agent_id: 'agent-11', event_type: 'info', message: 'Generated persona: Rev. Jimmy Whitmore (Wise Elder)' },
    { timestamp: fmt(540), phase: 'Phase 2', agent_id: 'agent-10', event_type: 'info', message: 'Generated persona: Daniella Cruz (Tough Cookie)' },
    { timestamp: fmt(570), phase: 'Phase 2', agent_id: 'agent-09', event_type: 'info', message: 'Generated persona: Kai Nakamura (Idealistic Outsider)' },
    { timestamp: fmt(600), phase: 'Phase 2', agent_id: 'agent-08', event_type: 'info', message: 'Generated persona: Heather Dawson (Southern Manipulator)' },
    { timestamp: fmt(630), phase: 'Phase 2', agent_id: 'agent-07', event_type: 'info', message: 'Generated persona: TJ Jackson (Loyal Soldier)' },
    { timestamp: fmt(660), phase: 'Phase 2', agent_id: 'agent-06', event_type: 'info', message: 'Generated persona: Victoria Ashford (Ice Queen Strategist)' },
    { timestamp: fmt(690), phase: 'Phase 2', agent_id: 'agent-05', event_type: 'info', message: 'Generated persona: Brett Kowalski (Class Clown)' },
    { timestamp: fmt(720), phase: 'Phase 2', agent_id: 'agent-04', event_type: 'info', message: 'Generated persona: Jasmine Williams (Empathic Caretaker)' },
    { timestamp: fmt(750), phase: 'Phase 2', agent_id: 'agent-03', event_type: 'info', message: 'Generated persona: David Chen (Quiet Observer)' },
    { timestamp: fmt(780), phase: 'Phase 2', agent_id: 'agent-02', event_type: 'info', message: 'Generated persona: Sofia Reyes (Social Butterfly)' },
    { timestamp: fmt(810), phase: 'Phase 2', agent_id: 'agent-01', event_type: 'info', message: 'Generated persona: Marcus Thompson (Alpha Competitor)' },
    { timestamp: fmt(850), phase: 'Phase 2', agent_id: null, event_type: 'info', message: 'Beginning Phase 2: Persona Generation via Opus' },
    { timestamp: fmt(900), phase: 'Phase 1', agent_id: null, event_type: 'success', message: 'Phase 1 complete: Knowledge base built with 847 documents' },
    { timestamp: fmt(1000), phase: 'Phase 1', agent_id: null, event_type: 'info', message: 'Embedding Big Brother seasons 1-25 gameplay data' },
    { timestamp: fmt(1100), phase: 'Phase 1', agent_id: null, event_type: 'info', message: 'Processing reality TV social dynamics research papers' },
    { timestamp: fmt(1200), phase: 'Phase 1', agent_id: null, event_type: 'info', message: 'Indexing archetype taxonomy and personality frameworks' },
    { timestamp: fmt(1400), phase: 'Phase 1', agent_id: null, event_type: 'info', message: 'Beginning Phase 1: Knowledge Base Construction' },
    { timestamp: fmt(1500), phase: 'Phase 1', agent_id: null, event_type: 'info', message: 'Pipeline initialized. Budget: $75.00. Target: 12 agents.' },
  ],
};
